/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Ajouter_Capteur (void)
{
  GtkWidget *Ajouter_Capteur;
  GtkWidget *fixed1;
  GtkWidget *entryMarque;
  GtkWidget *entryType;
  GtkWidget *entryID;
  GtkWidget *buttonAjouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *buttonAnnuler;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *labelMarque;
  GtkWidget *labelType;
  GtkWidget *labelID;
  GtkWidget *labelAchat;
  GtkWidget *labelEtat;
  GtkWidget *labelDatePanne;
  GtkWidget *comboboxdpjj;
  GtkWidget *comboboxdpmm;
  GtkWidget *comboboxdpaa;
  GtkWidget *radiobuttonNon_Defectieux;
  GSList *radiobuttonNon_Defectieux_group = NULL;
  GtkWidget *radiobuttonDefectieux;
  GtkWidget *comboboxdajj;
  GtkWidget *comboboxdamm;
  GtkWidget *comboboxdaaa;

  Ajouter_Capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajouter_Capteur), _("Ajouter Un Capteur"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Ajouter_Capteur), fixed1);

  entryMarque = gtk_entry_new ();
  gtk_widget_show (entryMarque);
  gtk_fixed_put (GTK_FIXED (fixed1), entryMarque, 160, 24);
  gtk_widget_set_size_request (entryMarque, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryMarque), 8226);

  entryType = gtk_entry_new ();
  gtk_widget_show (entryType);
  gtk_fixed_put (GTK_FIXED (fixed1), entryType, 160, 72);
  gtk_widget_set_size_request (entryType, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryType), 8226);

  entryID = gtk_entry_new ();
  gtk_widget_show (entryID);
  gtk_fixed_put (GTK_FIXED (fixed1), entryID, 160, 120);
  gtk_widget_set_size_request (entryID, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryID), 8226);

  buttonAjouter = gtk_button_new ();
  gtk_widget_show (buttonAjouter);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAjouter, 144, 312);
  gtk_widget_set_size_request (buttonAjouter, 98, 45);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonAjouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  buttonAnnuler = gtk_button_new ();
  gtk_widget_show (buttonAnnuler);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAnnuler, 264, 312);
  gtk_widget_set_size_request (buttonAnnuler, 98, 45);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonAnnuler), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  labelMarque = gtk_label_new (_("Marque"));
  gtk_widget_show (labelMarque);
  gtk_fixed_put (GTK_FIXED (fixed1), labelMarque, 72, 24);
  gtk_widget_set_size_request (labelMarque, 57, 25);

  labelType = gtk_label_new (_("Type"));
  gtk_widget_show (labelType);
  gtk_fixed_put (GTK_FIXED (fixed1), labelType, 80, 72);
  gtk_widget_set_size_request (labelType, 49, 25);

  labelID = gtk_label_new (_("ID"));
  gtk_widget_show (labelID);
  gtk_fixed_put (GTK_FIXED (fixed1), labelID, 80, 120);
  gtk_widget_set_size_request (labelID, 41, 25);

  labelAchat = gtk_label_new (_("Date d'achat"));
  gtk_widget_show (labelAchat);
  gtk_fixed_put (GTK_FIXED (fixed1), labelAchat, 48, 160);
  gtk_widget_set_size_request (labelAchat, 96, 24);

  labelEtat = gtk_label_new (_("Etat"));
  gtk_widget_show (labelEtat);
  gtk_fixed_put (GTK_FIXED (fixed1), labelEtat, 72, 200);
  gtk_widget_set_size_request (labelEtat, 56, 32);

  labelDatePanne = gtk_label_new (_("Date du panne"));
  gtk_widget_show (labelDatePanne);
  gtk_fixed_put (GTK_FIXED (fixed1), labelDatePanne, 40, 256);
  gtk_widget_set_size_request (labelDatePanne, 105, 24);

  comboboxdpjj = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxdpjj);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxdpjj, 160, 256);
  gtk_widget_set_size_request (comboboxdpjj, 57, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjj), _("31"));

  comboboxdpmm = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxdpmm);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxdpmm, 224, 256);
  gtk_widget_set_size_request (comboboxdpmm, 56, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmm), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmm), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmm), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmm), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmm), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmm), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmm), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmm), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmm), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmm), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmm), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmm), _("12"));

  comboboxdpaa = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxdpaa);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxdpaa, 288, 256);
  gtk_widget_set_size_request (comboboxdpaa, 72, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("1999"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2000"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2001"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2002"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2003"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2004"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2005"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2006"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2007"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2008"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2009"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2010"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2011"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2012"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2013"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2014"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2015"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2016"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2017"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2018"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2019"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2021"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2022"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2023"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2024"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2025"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2026"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2027"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2028"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2029"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaa), _("2030"));

  radiobuttonNon_Defectieux = gtk_radio_button_new_with_mnemonic (NULL, _("Non Defectieux"));
  gtk_widget_show (radiobuttonNon_Defectieux);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobuttonNon_Defectieux, 136, 200);
  gtk_widget_set_size_request (radiobuttonNon_Defectieux, 136, 32);
  GTK_WIDGET_SET_FLAGS (radiobuttonNon_Defectieux, GTK_CAN_DEFAULT);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonNon_Defectieux), radiobuttonNon_Defectieux_group);
  radiobuttonNon_Defectieux_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonNon_Defectieux));

  radiobuttonDefectieux = gtk_radio_button_new_with_mnemonic (NULL, _("Defectieux"));
  gtk_widget_show (radiobuttonDefectieux);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobuttonDefectieux, 280, 200);
  gtk_widget_set_size_request (radiobuttonDefectieux, 124, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonDefectieux), radiobuttonNon_Defectieux_group);
  radiobuttonNon_Defectieux_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonDefectieux));

  comboboxdajj = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxdajj);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxdajj, 160, 152);
  gtk_widget_set_size_request (comboboxdajj, 56, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajj), _("31"));

  comboboxdamm = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxdamm);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxdamm, 224, 152);
  gtk_widget_set_size_request (comboboxdamm, 56, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdamm), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdamm), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdamm), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdamm), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdamm), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdamm), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdamm), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdamm), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdamm), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdamm), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdamm), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdamm), _("12"));

  comboboxdaaa = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxdaaa);
  gtk_fixed_put (GTK_FIXED (fixed1), comboboxdaaa, 288, 152);
  gtk_widget_set_size_request (comboboxdaaa, 72, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("1999"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2000"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2001"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2002"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2003"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2004"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2005"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2006"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2007"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2008"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2009"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2010"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2011"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2012"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2013"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2014"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2015"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2016"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2017"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2018"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2019"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2021"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2022"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2023"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2024"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2025"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2026"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2027"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2028"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2029"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaa), _("2030"));

  g_signal_connect ((gpointer) buttonAjouter, "clicked",
                    G_CALLBACK (on_buttonAjouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAnnuler, "clicked",
                    G_CALLBACK (on_buttonAnnuler_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonNon_Defectieux, "toggled",
                    G_CALLBACK (on_radiobuttonNon_Defectieux_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonDefectieux, "toggled",
                    G_CALLBACK (on_radiobuttonDefectieux_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter_Capteur, Ajouter_Capteur, "Ajouter_Capteur");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, entryMarque, "entryMarque");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, entryType, "entryType");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, entryID, "entryID");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, buttonAjouter, "buttonAjouter");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, image1, "image1");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, label1, "label1");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, buttonAnnuler, "buttonAnnuler");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, image2, "image2");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, label2, "label2");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, labelMarque, "labelMarque");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, labelType, "labelType");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, labelID, "labelID");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, labelAchat, "labelAchat");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, labelEtat, "labelEtat");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, labelDatePanne, "labelDatePanne");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, comboboxdpjj, "comboboxdpjj");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, comboboxdpmm, "comboboxdpmm");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, comboboxdpaa, "comboboxdpaa");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, radiobuttonNon_Defectieux, "radiobuttonNon_Defectieux");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, radiobuttonDefectieux, "radiobuttonDefectieux");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, comboboxdajj, "comboboxdajj");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, comboboxdamm, "comboboxdamm");
  GLADE_HOOKUP_OBJECT (Ajouter_Capteur, comboboxdaaa, "comboboxdaaa");

  gtk_widget_grab_default (radiobuttonNon_Defectieux);
  return Ajouter_Capteur;
}

GtkWidget*
create_Ajouter_Valeur (void)
{
  GtkWidget *Ajouter_Valeur;
  GtkWidget *fixed2;
  GtkWidget *labelValeur;
  GtkWidget *labelDprise;
  GtkWidget *labelHoraire;
  GtkObject *spinbuttonHeure_adj;
  GtkWidget *spinbuttonHeure;
  GtkObject *spinbuttonMinute_adj;
  GtkWidget *spinbuttonMinute;
  GtkWidget *comboboxPrisejj;
  GtkWidget *comboboxPrisemm;
  GtkWidget *comboboxPriseaa;
  GtkWidget *buttonAjout;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *buttonAnnul;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;
  GtkWidget *entryValeur_C;

  Ajouter_Valeur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajouter_Valeur), _("Ajouter Valeur"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Ajouter_Valeur), fixed2);

  labelValeur = gtk_label_new (_("Valeur"));
  gtk_widget_show (labelValeur);
  gtk_fixed_put (GTK_FIXED (fixed2), labelValeur, 56, 64);
  gtk_widget_set_size_request (labelValeur, 73, 25);

  labelDprise = gtk_label_new (_("Date prise"));
  gtk_widget_show (labelDprise);
  gtk_fixed_put (GTK_FIXED (fixed2), labelDprise, 48, 112);
  gtk_widget_set_size_request (labelDprise, 73, 33);

  labelHoraire = gtk_label_new (_("Horaire"));
  gtk_widget_show (labelHoraire);
  gtk_fixed_put (GTK_FIXED (fixed2), labelHoraire, 56, 176);
  gtk_widget_set_size_request (labelHoraire, 65, 25);

  spinbuttonHeure_adj = gtk_adjustment_new (0, 0, 23, 1, 10, 10);
  spinbuttonHeure = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonHeure_adj), 1, 0);
  gtk_widget_show (spinbuttonHeure);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonHeure, 128, 176);
  gtk_widget_set_size_request (spinbuttonHeure, 60, 27);

  spinbuttonMinute_adj = gtk_adjustment_new (0, 0, 59, 1, 10, 10);
  spinbuttonMinute = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonMinute_adj), 1, 0);
  gtk_widget_show (spinbuttonMinute);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonMinute, 200, 176);
  gtk_widget_set_size_request (spinbuttonMinute, 60, 27);

  comboboxPrisejj = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxPrisejj);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxPrisejj, 128, 112);
  gtk_widget_set_size_request (comboboxPrisejj, 48, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisejj), _("31"));

  comboboxPrisemm = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxPrisemm);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxPrisemm, 184, 112);
  gtk_widget_set_size_request (comboboxPrisemm, 48, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisemm), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisemm), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisemm), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisemm), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisemm), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisemm), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisemm), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisemm), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisemm), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisemm), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisemm), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPrisemm), _("12"));

  comboboxPriseaa = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxPriseaa);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxPriseaa, 240, 112);
  gtk_widget_set_size_request (comboboxPriseaa, 88, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("1999"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2000"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2001"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2002"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2003"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2004"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2005"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2006"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2007"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2008"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2009"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2010"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2011"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2012"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2013"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2014"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2015"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2016"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2017"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2018"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2019"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2021"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2022"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2023"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2024"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2025"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2026"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2027"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2028"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2029"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxPriseaa), _("2030"));

  buttonAjout = gtk_button_new ();
  gtk_widget_show (buttonAjout);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonAjout, 112, 248);
  gtk_widget_set_size_request (buttonAjout, 98, 37);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonAjout), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  buttonAnnul = gtk_button_new ();
  gtk_widget_show (buttonAnnul);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonAnnul, 240, 248);
  gtk_widget_set_size_request (buttonAnnul, 98, 37);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonAnnul), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  entryValeur_C = gtk_entry_new ();
  gtk_widget_show (entryValeur_C);
  gtk_fixed_put (GTK_FIXED (fixed2), entryValeur_C, 128, 64);
  gtk_widget_set_size_request (entryValeur_C, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryValeur_C), 8226);

  g_signal_connect ((gpointer) buttonAjout, "clicked",
                    G_CALLBACK (on_buttonAjout_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAnnul, "clicked",
                    G_CALLBACK (on_buttonAnnul_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter_Valeur, Ajouter_Valeur, "Ajouter_Valeur");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, labelValeur, "labelValeur");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, labelDprise, "labelDprise");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, labelHoraire, "labelHoraire");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, spinbuttonHeure, "spinbuttonHeure");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, spinbuttonMinute, "spinbuttonMinute");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, comboboxPrisejj, "comboboxPrisejj");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, comboboxPrisemm, "comboboxPrisemm");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, comboboxPriseaa, "comboboxPriseaa");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, buttonAjout, "buttonAjout");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, image3, "image3");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, label3, "label3");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, buttonAnnul, "buttonAnnul");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, image4, "image4");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, label4, "label4");
  GLADE_HOOKUP_OBJECT (Ajouter_Valeur, entryValeur_C, "entryValeur_C");

  return Ajouter_Valeur;
}

GtkWidget*
create_Recherche (void)
{
  GtkWidget *Recherche;
  GtkWidget *fixed3;
  GtkWidget *entryIDCherche;
  GtkWidget *entryMarqueModif;
  GtkWidget *entryTypeModif;
  GtkWidget *entryIDModif;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *comboboxdammModif;
  GtkWidget *radiobutton1modif;
  GSList *radiobutton1modif_group = NULL;
  GtkWidget *label25;
  GtkWidget *comboboxdaaaModif;
  GtkWidget *radiobutton2modif;
  GtkWidget *comboboxdajjModif;
  GtkWidget *comboboxdpjjModif;
  GtkWidget *comboboxdpmmModif;
  GtkWidget *comboboxdpaaModif;
  GtkWidget *buttonAnnultt;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image23;
  GtkWidget *label28;
  GtkWidget *buttonSupprim;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image22;
  GtkWidget *label27;
  GtkWidget *buttonModifier;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image21;
  GtkWidget *label26;
  GtkWidget *buttonCherche;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label5;

  Recherche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Recherche), _("Recherche"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Recherche), fixed3);

  entryIDCherche = gtk_entry_new ();
  gtk_widget_show (entryIDCherche);
  gtk_fixed_put (GTK_FIXED (fixed3), entryIDCherche, 256, 16);
  gtk_widget_set_size_request (entryIDCherche, 176, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryIDCherche), 8226);

  entryMarqueModif = gtk_entry_new ();
  gtk_widget_show (entryMarqueModif);
  gtk_fixed_put (GTK_FIXED (fixed3), entryMarqueModif, 160, 96);
  gtk_widget_set_size_request (entryMarqueModif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryMarqueModif), 8226);

  entryTypeModif = gtk_entry_new ();
  gtk_widget_show (entryTypeModif);
  gtk_fixed_put (GTK_FIXED (fixed3), entryTypeModif, 160, 136);
  gtk_widget_set_size_request (entryTypeModif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryTypeModif), 8226);

  entryIDModif = gtk_entry_new ();
  gtk_widget_show (entryIDModif);
  gtk_fixed_put (GTK_FIXED (fixed3), entryIDModif, 160, 176);
  gtk_widget_set_size_request (entryIDModif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryIDModif), 8226);

  label23 = gtk_label_new (_("Date d'achat"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 48, 216);
  gtk_widget_set_size_request (label23, 96, 24);

  label24 = gtk_label_new (_("Etat"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed3), label24, 80, 264);
  gtk_widget_set_size_request (label24, 56, 32);

  label20 = gtk_label_new (_("Marque"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 80, 96);
  gtk_widget_set_size_request (label20, 57, 25);

  label21 = gtk_label_new (_("Type"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 80, 136);
  gtk_widget_set_size_request (label21, 49, 25);

  label22 = gtk_label_new (_("ID"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 88, 176);
  gtk_widget_set_size_request (label22, 41, 25);

  comboboxdammModif = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxdammModif);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxdammModif, 224, 216);
  gtk_widget_set_size_request (comboboxdammModif, 56, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdammModif), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdammModif), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdammModif), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdammModif), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdammModif), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdammModif), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdammModif), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdammModif), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdammModif), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdammModif), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdammModif), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdammModif), _("12"));

  radiobutton1modif = gtk_radio_button_new_with_mnemonic (NULL, _("Non Defectieux"));
  gtk_widget_show (radiobutton1modif);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton1modif, 160, 264);
  gtk_widget_set_size_request (radiobutton1modif, 136, 32);
  GTK_WIDGET_SET_FLAGS (radiobutton1modif, GTK_CAN_DEFAULT);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1modif), radiobutton1modif_group);
  radiobutton1modif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1modif));

  label25 = gtk_label_new (_("Date du panne"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed3), label25, 40, 312);
  gtk_widget_set_size_request (label25, 105, 24);

  comboboxdaaaModif = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxdaaaModif);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxdaaaModif, 288, 216);
  gtk_widget_set_size_request (comboboxdaaaModif, 72, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("1999"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2000"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2001"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2002"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2003"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2004"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2005"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2006"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2007"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2008"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2009"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2010"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2011"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2012"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2013"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2014"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2015"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2016"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2017"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2018"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2019"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2021"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2022"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2023"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2024"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2025"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2026"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2027"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2028"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2029"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdaaaModif), _("2030"));

  radiobutton2modif = gtk_radio_button_new_with_mnemonic (NULL, _("Defectieux"));
  gtk_widget_show (radiobutton2modif);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton2modif, 304, 264);
  gtk_widget_set_size_request (radiobutton2modif, 128, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2modif), radiobutton1modif_group);
  radiobutton1modif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2modif));

  comboboxdajjModif = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxdajjModif);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxdajjModif, 160, 216);
  gtk_widget_set_size_request (comboboxdajjModif, 56, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdajjModif), _("31"));

  comboboxdpjjModif = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxdpjjModif);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxdpjjModif, 160, 312);
  gtk_widget_set_size_request (comboboxdpjjModif, 57, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpjjModif), _("31"));

  comboboxdpmmModif = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxdpmmModif);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxdpmmModif, 224, 312);
  gtk_widget_set_size_request (comboboxdpmmModif, 56, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmmModif), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmmModif), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmmModif), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmmModif), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmmModif), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmmModif), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmmModif), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmmModif), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmmModif), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmmModif), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmmModif), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpmmModif), _("12"));

  comboboxdpaaModif = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxdpaaModif);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxdpaaModif, 288, 312);
  gtk_widget_set_size_request (comboboxdpaaModif, 72, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("1999"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2000"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2001"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2002"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2003"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2004"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2005"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2006"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2007"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2008"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2009"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2010"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2011"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2012"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2013"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2014"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2015"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2016"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2017"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2018"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2019"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2021"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2022"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2023"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2024"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2025"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2026"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2027"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2028"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2029"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxdpaaModif), _("2030"));

  buttonAnnultt = gtk_button_new ();
  gtk_widget_show (buttonAnnultt);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonAnnultt, 344, 384);
  gtk_widget_set_size_request (buttonAnnultt, 104, 40);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (buttonAnnultt), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image23 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox22), image23, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox22), label28, FALSE, FALSE, 0);

  buttonSupprim = gtk_button_new ();
  gtk_widget_show (buttonSupprim);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonSupprim, 208, 384);
  gtk_widget_set_size_request (buttonSupprim, 112, 40);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (buttonSupprim), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image22 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox21), image22, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox21), label27, FALSE, FALSE, 0);

  buttonModifier = gtk_button_new ();
  gtk_widget_show (buttonModifier);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonModifier, 88, 384);
  gtk_widget_set_size_request (buttonModifier, 96, 40);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (buttonModifier), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image21 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox20), image21, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox20), label26, FALSE, FALSE, 0);

  buttonCherche = gtk_button_new ();
  gtk_widget_show (buttonCherche);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonCherche, 432, 16);
  gtk_widget_set_size_request (buttonCherche, 48, 48);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonCherche), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) radiobutton1modif, "toggled",
                    G_CALLBACK (on_radiobutton1modif_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2modif, "toggled",
                    G_CALLBACK (on_radiobutton2modif_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonAnnultt, "clicked",
                    G_CALLBACK (on_buttonAnnultt_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSupprim, "clicked",
                    G_CALLBACK (on_buttonSupprim_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModifier, "clicked",
                    G_CALLBACK (on_buttonModifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonCherche, "clicked",
                    G_CALLBACK (on_buttonCherche_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Recherche, Recherche, "Recherche");
  GLADE_HOOKUP_OBJECT (Recherche, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Recherche, entryIDCherche, "entryIDCherche");
  GLADE_HOOKUP_OBJECT (Recherche, entryMarqueModif, "entryMarqueModif");
  GLADE_HOOKUP_OBJECT (Recherche, entryTypeModif, "entryTypeModif");
  GLADE_HOOKUP_OBJECT (Recherche, entryIDModif, "entryIDModif");
  GLADE_HOOKUP_OBJECT (Recherche, label23, "label23");
  GLADE_HOOKUP_OBJECT (Recherche, label24, "label24");
  GLADE_HOOKUP_OBJECT (Recherche, label20, "label20");
  GLADE_HOOKUP_OBJECT (Recherche, label21, "label21");
  GLADE_HOOKUP_OBJECT (Recherche, label22, "label22");
  GLADE_HOOKUP_OBJECT (Recherche, comboboxdammModif, "comboboxdammModif");
  GLADE_HOOKUP_OBJECT (Recherche, radiobutton1modif, "radiobutton1modif");
  GLADE_HOOKUP_OBJECT (Recherche, label25, "label25");
  GLADE_HOOKUP_OBJECT (Recherche, comboboxdaaaModif, "comboboxdaaaModif");
  GLADE_HOOKUP_OBJECT (Recherche, radiobutton2modif, "radiobutton2modif");
  GLADE_HOOKUP_OBJECT (Recherche, comboboxdajjModif, "comboboxdajjModif");
  GLADE_HOOKUP_OBJECT (Recherche, comboboxdpjjModif, "comboboxdpjjModif");
  GLADE_HOOKUP_OBJECT (Recherche, comboboxdpmmModif, "comboboxdpmmModif");
  GLADE_HOOKUP_OBJECT (Recherche, comboboxdpaaModif, "comboboxdpaaModif");
  GLADE_HOOKUP_OBJECT (Recherche, buttonAnnultt, "buttonAnnultt");
  GLADE_HOOKUP_OBJECT (Recherche, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (Recherche, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (Recherche, image23, "image23");
  GLADE_HOOKUP_OBJECT (Recherche, label28, "label28");
  GLADE_HOOKUP_OBJECT (Recherche, buttonSupprim, "buttonSupprim");
  GLADE_HOOKUP_OBJECT (Recherche, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (Recherche, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (Recherche, image22, "image22");
  GLADE_HOOKUP_OBJECT (Recherche, label27, "label27");
  GLADE_HOOKUP_OBJECT (Recherche, buttonModifier, "buttonModifier");
  GLADE_HOOKUP_OBJECT (Recherche, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (Recherche, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (Recherche, image21, "image21");
  GLADE_HOOKUP_OBJECT (Recherche, label26, "label26");
  GLADE_HOOKUP_OBJECT (Recherche, buttonCherche, "buttonCherche");
  GLADE_HOOKUP_OBJECT (Recherche, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Recherche, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Recherche, image5, "image5");
  GLADE_HOOKUP_OBJECT (Recherche, label5, "label5");

  gtk_widget_grab_default (radiobutton1modif);
  return Recherche;
}

GtkWidget*
create_First_page (void)
{
  GtkWidget *First_page;
  GtkWidget *fixed7;
  GtkWidget *labelBienvenue;
  GtkWidget *button_Ajout;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label13;
  GtkWidget *button_Cherche;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label14;
  GtkWidget *button_Modif;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label15;
  GtkWidget *button_Supp;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label16;
  GtkWidget *button_Afficher;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label17;

  First_page = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (First_page), _("Bienvenue"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (First_page), fixed7);

  labelBienvenue = gtk_label_new (_("Bienvenue "));
  gtk_widget_show (labelBienvenue);
  gtk_fixed_put (GTK_FIXED (fixed7), labelBienvenue, 72, 32);
  gtk_widget_set_size_request (labelBienvenue, 136, 40);

  button_Ajout = gtk_button_new ();
  gtk_widget_show (button_Ajout);
  gtk_fixed_put (GTK_FIXED (fixed7), button_Ajout, 56, 88);
  gtk_widget_set_size_request (button_Ajout, 136, 48);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_Ajout), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox13), label13, FALSE, FALSE, 0);

  button_Cherche = gtk_button_new ();
  gtk_widget_show (button_Cherche);
  gtk_fixed_put (GTK_FIXED (fixed7), button_Cherche, 56, 152);
  gtk_widget_set_size_request (button_Cherche, 136, 56);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_Cherche), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox14), label14, FALSE, FALSE, 0);

  button_Modif = gtk_button_new ();
  gtk_widget_show (button_Modif);
  gtk_fixed_put (GTK_FIXED (fixed7), button_Modif, 56, 224);
  gtk_widget_set_size_request (button_Modif, 136, 48);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_Modif), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox15), label15, FALSE, FALSE, 0);

  button_Supp = gtk_button_new ();
  gtk_widget_show (button_Supp);
  gtk_fixed_put (GTK_FIXED (fixed7), button_Supp, 56, 288);
  gtk_widget_set_size_request (button_Supp, 136, 56);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button_Supp), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox16), label16, FALSE, FALSE, 0);

  button_Afficher = gtk_button_new ();
  gtk_widget_show (button_Afficher);
  gtk_fixed_put (GTK_FIXED (fixed7), button_Afficher, 56, 360);
  gtk_widget_set_size_request (button_Afficher, 136, 48);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button_Afficher), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox17), label17, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_Ajout, "clicked",
                    G_CALLBACK (on_button_Ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_Cherche, "clicked",
                    G_CALLBACK (on_button_Cherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_Modif, "clicked",
                    G_CALLBACK (on_button_Modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_Supp, "clicked",
                    G_CALLBACK (on_button_Supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_Afficher, "clicked",
                    G_CALLBACK (on_button_Afficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (First_page, First_page, "First_page");
  GLADE_HOOKUP_OBJECT (First_page, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (First_page, labelBienvenue, "labelBienvenue");
  GLADE_HOOKUP_OBJECT (First_page, button_Ajout, "button_Ajout");
  GLADE_HOOKUP_OBJECT (First_page, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (First_page, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (First_page, image13, "image13");
  GLADE_HOOKUP_OBJECT (First_page, label13, "label13");
  GLADE_HOOKUP_OBJECT (First_page, button_Cherche, "button_Cherche");
  GLADE_HOOKUP_OBJECT (First_page, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (First_page, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (First_page, image14, "image14");
  GLADE_HOOKUP_OBJECT (First_page, label14, "label14");
  GLADE_HOOKUP_OBJECT (First_page, button_Modif, "button_Modif");
  GLADE_HOOKUP_OBJECT (First_page, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (First_page, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (First_page, image15, "image15");
  GLADE_HOOKUP_OBJECT (First_page, label15, "label15");
  GLADE_HOOKUP_OBJECT (First_page, button_Supp, "button_Supp");
  GLADE_HOOKUP_OBJECT (First_page, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (First_page, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (First_page, image16, "image16");
  GLADE_HOOKUP_OBJECT (First_page, label16, "label16");
  GLADE_HOOKUP_OBJECT (First_page, button_Afficher, "button_Afficher");
  GLADE_HOOKUP_OBJECT (First_page, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (First_page, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (First_page, image17, "image17");
  GLADE_HOOKUP_OBJECT (First_page, label17, "label17");

  return First_page;
}

GtkWidget*
create_Affichage (void)
{
  GtkWidget *Affichage;
  GtkWidget *fixed8;
  GtkWidget *treeviewAffichage;
  GtkWidget *Return;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label18;
  GtkWidget *buttonok_afficher;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image20;
  GtkWidget *label19;

  Affichage = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Affichage), _("Affichage"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (Affichage), fixed8);

  treeviewAffichage = gtk_tree_view_new ();
  gtk_widget_show (treeviewAffichage);
  gtk_fixed_put (GTK_FIXED (fixed8), treeviewAffichage, 40, 72);
  gtk_widget_set_size_request (treeviewAffichage, 464, 352);

  Return = gtk_button_new ();
  gtk_widget_show (Return);
  gtk_fixed_put (GTK_FIXED (fixed8), Return, 352, 440);
  gtk_widget_set_size_request (Return, 130, 37);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (Return), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox18), label18, FALSE, FALSE, 0);

  buttonok_afficher = gtk_button_new ();
  gtk_widget_show (buttonok_afficher);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonok_afficher, 120, 440);
  gtk_widget_set_size_request (buttonok_afficher, 128, 40);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (buttonok_afficher), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image20 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox19), image20, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox19), label19, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeviewAffichage, "row_activated",
                    G_CALLBACK (on_treeviewAffichage_row_activated),
                    NULL);
  g_signal_connect ((gpointer) Return, "clicked",
                    G_CALLBACK (on_Return_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonok_afficher, "clicked",
                    G_CALLBACK (on_buttonok_afficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Affichage, Affichage, "Affichage");
  GLADE_HOOKUP_OBJECT (Affichage, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (Affichage, treeviewAffichage, "treeviewAffichage");
  GLADE_HOOKUP_OBJECT (Affichage, Return, "Return");
  GLADE_HOOKUP_OBJECT (Affichage, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (Affichage, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (Affichage, image18, "image18");
  GLADE_HOOKUP_OBJECT (Affichage, label18, "label18");
  GLADE_HOOKUP_OBJECT (Affichage, buttonok_afficher, "buttonok_afficher");
  GLADE_HOOKUP_OBJECT (Affichage, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (Affichage, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Affichage, image20, "image20");
  GLADE_HOOKUP_OBJECT (Affichage, label19, "label19");

  return Affichage;
}

