/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Ajouter_Capteur (void);
GtkWidget* create_Ajouter_Valeur (void);
GtkWidget* create_Recherche (void);
GtkWidget* create_First_page (void);
GtkWidget* create_Affichage (void);
