/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Ajouter_Capteur;
  GtkWidget *Ajouter_Valeur;
  GtkWidget *Recherche;
  GtkWidget *Result_Search;
  GtkWidget *Modifier;
  GtkWidget *Supprimer;
  GtkWidget *First_page;
  GtkWidget *Affichage;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  /*Ajouter_Capteur = create_Ajouter_Capteur ();
  gtk_widget_show (Ajouter_Capteur);
  Ajouter_Valeur = create_Ajouter_Valeur ();
  gtk_widget_show (Ajouter_Valeur);
  Recherche = create_Recherche ();
  gtk_widget_show (Recherche);
  */
  First_page = create_First_page ();
  gtk_widget_show (First_page);
  /*Affichage = create_Affichage ();
  gtk_widget_show (Affichage);*/

  gtk_main ();
  return 0;
}

